### ISSUE TITLE
vault-secrets-webhook fails to deploy

### ISSUE THREAD

**Issue by JohnHoward9** [banzaicloud/banzai-charts#595]
Helm deployment of vault-secrets-webhook fails

To Reproduce
kubectl apply -f operator/deploy/rbac.yaml
kubectl apply -f operator/deploy/operator.yaml
kubectl apply -f operator/deploy/cr.yaml
helm init
helm repo add banzaicloud-stable http://kubernetes-charts.banzaicloud.com/branch/master
helm upgrade --install wmwh banzaicloud-stable/vault-secrets-webhook

Expected behavior
vault-secrets-webhook deployed

Actual behavior
Replica set failure
Name:           wmwh-vault-secrets-webhook-545f4df9dc
Namespace:      default
Selector:       app=vault-secrets-webhook,pod-template-hash=1019089587,release=wmwh
Labels:         app=vault-secrets-webhook
                pod-template-hash=1019089587
                release=wmwh
Annotations:    deployment.kubernetes.io/desired-replicas=1
                deployment.kubernetes.io/max-replicas=2
                deployment.kubernetes.io/revision=1
Controlled By:  Deployment/wmwh-vault-secrets-webhook
Replicas:       0 current / 1 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=vault-secrets-webhook
                    pod-template-hash=1019089587
                    release=wmwh
  Service Account:  wmwh-vault-secrets-webhook
  Containers:
   vault-secrets-webhook:
    Image:      banzaicloud/vault-secrets-webhook:latest
    Port:       443/TCP
    Host Port:  0/TCP
    Environment:
      TLS_CERT_FILE:         /var/serving-cert/servingCert
      TLS_PRIVATE_KEY_FILE:  /var/serving-cert/servingKey
    Mounts:
      /var/serving-cert from serving-cert (rw)
  Volumes:
   serving-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  wmwh-vault-secrets-webhook
    Optional:    false
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age               From                   Message
  ----     ------        ----              ----                   -------
  Warning  FailedCreate  1m                replicaset-controller  Error creating: Internal error occurred: failed calling admission webhook "pods.vault-secrets-webhook.admission.banzaicloud.com": Post https://wmwh-vault-secrets-webhook.default.svc:443/pods?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  FailedCreate  11s (x3 over 1m)  replicaset-controller  Error creating: Internal error occurred: failed calling admission webhook "pods.vault-secrets-webhook.admission.banzaicloud.com": Post https://wmwh-vault-secrets-webhook.default.svc:443/pods?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Versions
Helm v2.12.0
K8s v1.11.5

**Comment by bonifaido** [comment]
Hi @JohnHoward9! Could you please post some logs from the webhook pod itself?

**Comment by JohnHoward9** [comment]
Hi @bonifaido 

It doesn't look like the pod is created, though there is a webhook entry in services and deployments!  kubectl get pods --all-namespaces results in:
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
default       vault-0                                 3/3       Running   1          1h
default       vault-configurer-77b69fb797-9x4ph       1/1       Running   0          1h
default       vault-operator-5d4cffd545-kqx5f         1/1       Running   0          1h
kube-system   heapster-5d6f9b846c-kgrb9               2/2       Running   0          2h
kube-system   kube-dns-v20-7c7d7d4c66-fnhbw           4/4       Running   0          2h
kube-system   kube-dns-v20-7c7d7d4c66-t5k85           4/4       Running   0          2h
kube-system   kube-proxy-q7vbz                        1/1       Running   0          1h
kube-system   kube-svc-redirect-hl5kr                 2/2       Running   0          1h
kube-system   kubernetes-dashboard-68f468887f-cdsmj   1/1       Running   0          2h
kube-system   metrics-server-5cbc77f79f-fwqq2         1/1       Running   0          2h
kube-system   tiller-deploy-6d7964547c-f9flw          1/1       Running   0          1h
kube-system   tunnelfront-66f6ccb89b-gvg5m            1/1       Running   0          2h

Not sure if it is relevant.  This is a basic single node AKS cluster

**Comment by bonifaido** [comment]
Okay, I think the Deployment resource of the webhook couldn't set up all the required replicas because of some reason, we need to check the Deployment and the ReplicaSet of the webhook with kubectl describe, could you please paste those outputs?

**Comment by JohnHoward9** [comment]
Added file with describes for webhook

[webhook-describe.txt](https://github.com/banzaicloud/banzai-charts/files/2733991/webhook-describe.txt)

**Comment by bonifaido** [comment]
Okay, I managed to reproduce it on AKS, but it is not specific to AKS, it is an ordering issue between the Kubernetes resource. The `MutatingWebhookConfiguration` gets created before the actual backend `Pod` which serves as the webhook itself, Kubernetes would like to mutate that pod as well, but it is not ready to mutate yet (infinite recursion in logic). I will fix this issue with a namespace selector: https://github.com/kubernetes/api/blob/master/admissionregistration/v1beta1/types.go#L209

**Comment by JohnHoward9** [comment]
thanks.

I'd like to get a working reference of Azure, but eventually we would like to use helm charts for the deployments.  I'm assuming I would need to use the banzai vault, the vault_operator and the vault_secrets_webhook helm charts, with the appropriate Azure config (blob storage and Azure KV for unseal keys).  Would that be the right approach?

**Comment by bonifaido** [comment]
Yes, you can use the Banzai Vault Operator but also the Banzai Vault Helm chart as well, you only have to have the Kubernetes auth backend enabled in Vault, and if that is enabled it doesn't matter what kind of Vault you are using from the Vault Secrets Webhook point of view. I hope this helps, please feel free to ask any questions, I can help you set up a fully working Banzai Vault on Azure.

**Comment by bonifaido** [comment]
@JohnHoward9 the original issue has been resolved via #596, please try it if it works out for you, see comments on the PR how to use it.

**Comment by JohnHoward9** [comment]
Thanks, it's all working now.  

I'll move on to the Helm charts with Azure storage and Azure KV seal

Thanks again for all your help

**Comment by innovia** [comment]
I think it's key to emphasis on docs

the namespace must match the release name otherwise it fails

**Comment by bonifaido** [comment]
The release namespace will be ignored, but it doesn't have to match the release name.

https://github.com/banzaicloud/banzai-charts/blob/master/vault-secrets-webhook/templates/apiservice-webhook.yaml#L47

**Comment by innovia** [comment]
Im still getting an issue:

If i purge the install and install it works. but when killing the pod it doesn't comeback up

```  Warning  FailedCreate  12s (x14 over 103s)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "pods.vault-secrets-webhook.admission.server.com": Post https://vault-secrets-webhook.vault-secrets-webhook.svc:443/pods?timeout=30s: dial tcp 10.101.104.145:443: connect: connection refused```

**Comment by bonifaido** [comment]
Please run `kubectl describe namespace vault-secrets-webhook` to see if the namespace has the correct labels for filtering it.

**Comment by innovia** [comment]
none

```
Name:         vault-secrets-webhook
Labels:       <none>
Annotations:  <none>
Status:       Active

No resource quota.

No resource limits.
```

**Comment by innovia** [comment]
i created the namespace manually is that why?

**Comment by bonifaido** [comment]
Yes, please add a label to the namespace called:

```
labels:
  name: vault-secrets-webhook
```

**Comment by innovia** [comment]
Thanks!

We should add this to the docs - it's not clear enough and can be easily missed

I was wondering what name is and couldn't figure it out

**Comment by bonifaido** [comment]
Would you mind submitting a PR for this?

**Comment by innovia** [comment]
sure 

should we do this in the chart or just instructions on the readme?

**Comment by bonifaido** [comment]
Just in the README I think for now.

**Comment by innovia** [comment]
ok
